export const SEED_VERSION = 12;

import avatarLA from '../recursos/avatares/la.svg';
import avatarMS from '../recursos/avatares/ms.svg';
import avatarFP from '../recursos/avatares/fp.svg';
import avatarJP from '../recursos/avatares/jp.svg';
import avatarML from '../recursos/avatares/ml.svg';
import avatarCR from '../recursos/avatares/cr.svg';
import avatarLT from '../recursos/avatares/lt.svg';
import avatarPH from '../recursos/avatares/ph.svg';

export const CATEGORIAS = [
  { valor: 'almacen', etiqueta: 'Almacén' },
  { valor: 'estiba', etiqueta: 'Estiba' },
  { valor: 'reposicion', etiqueta: 'Reposición' },
  { valor: 'promotoria', etiqueta: 'Promotoría' },
  { valor: 'eventos', etiqueta: 'Eventos' },
  { valor: 'limpieza', etiqueta: 'Limpieza' },
  { valor: 'seguridad', etiqueta: 'Seguridad' },
  { valor: 'atencion_cliente', etiqueta: 'Atención al cliente' },
];

export const DISTRITOS = [
  'San Miguel',
  'Miraflores',
  'Los Olivos',
  'Ate',
  'Callao',
  'La Molina',
  'San Juan de Lurigancho',
  'Surco',
  'San Martín de Porres',
  'Villa El Salvador',
  'Chorrillos',
  'San Borja',
];

export const TIPOS_CONTRATO = [
  'Tiempo completo',
  'Medio tiempo',
  'Por turnos',
  'Fin de semana',
];
export const NIVELES_EXPERIENCIA = [
  'Sin experiencia',
  'Básica',
  'Intermedia',
  'Avanzada',
];

export const usuariosIniciales = [
  { id: 'u1', nombre: 'Logística Andina', email: 'empresa1@workhoy.com', password: '123456', rol: 'empresa', distrito: 'Callao', telefono: '987111000', avatar: avatarLA, rubro: 'Logística y almacenaje', desde: 2012, colaboradores: '+200 colaboradores', descripcion: 'Logística Andina es una empresa de logística y almacenaje con más de 14 años de trayectoria en el Callao. Nos dedicamos a la recepción, distribución y despacho de mercadería para compañías de retail e industria. Buscamos personal responsable y con ganas de crecer dentro de nuestro equipo de más de 200 colaboradores.' },
  { id: 'u2', nombre: 'Mega Store de Lima', email: 'empresa2@workhoy.com', password: '123456', rol: 'empresa', distrito: 'Miraflores', telefono: '987222000', avatar: avatarMS, rubro: 'Retail y tiendas por departamento', desde: 2008, colaboradores: '+1,500 colaboradores', descripcion: 'Mega Store de Lima es una cadena de tiendas por departamento con más de 15 años en el rubro retail. Nos dedicamos a la venta de moda, tecnología y hogar en nuestras sedes de Lima y provincias. Buscamos personas con vocación de servicio para sumarse a nuestro equipo de más de 1,500 colaboradores.' },
  { id: 'u3', nombre: 'Festivales del Perú', email: 'empresa3@workhoy.com', password: '123456', rol: 'empresa', distrito: 'Surco', telefono: '987333000', avatar: avatarFP, rubro: 'Eventos y ferias corporativas', desde: 2015, colaboradores: '+80 colaboradores', descripcion: 'Festivales del Perú es una productora de eventos y ferias corporativas fundada en 2015. Nos dedicamos a organizar ferias, conciertos y convenciones en todo Lima. Buscamos personal motivado y proactivo para unirse a nuestro equipo de más de 80 colaboradores.' },
  { id: 'u4', nombre: 'Juan Pérez', email: 'juan@workhoy.com', password: '123456', rol: 'trabajador', distrito: 'Miraflores', telefono: '987444000', avatar: avatarJP },
  { id: 'u5', nombre: 'María López', email: 'maria@workhoy.com', password: '123456', rol: 'trabajador', distrito: 'Los Olivos', telefono: '987555000', avatar: avatarML },
  { id: 'u6', nombre: 'Carlos Reyes', email: 'carlos@workhoy.com', password: '123456', rol: 'trabajador', distrito: 'Ate', telefono: '987666000', avatar: avatarCR },
  { id: 'u7', nombre: 'Lucía Torres', email: 'lucia@workhoy.com', password: '123456', rol: 'trabajador', distrito: 'La Molina', telefono: '987777000', avatar: avatarLT },
  { id: 'u8', nombre: 'Pedro Huamán', email: 'pedro@workhoy.com', password: '123456', rol: 'trabajador', distrito: 'Callao', telefono: '987888000', avatar: avatarPH },
];

export const vacantesIniciales = [
  {
    id: 'v1',
    empresaId: 'u1',
    titulo: 'Operario de almacén',
    categoria: 'almacen',
    distrito: 'Callao',
    sueldo: 75,
    horarios: ['07:00 a 15:00', '15:00 a 23:00'],
    horario: 'Lun a Sáb 7am - 3pm',
    tipoContrato: 'Tiempo completo',
    nivelExperiencia: 'Básica',
    idiomas: 'Español',
    vacantesDisponibles: 3,
    requisitos: [
      'Disponibilidad inmediata',
      'Experiencia en almacén (deseable)',
      'Puntualidad y responsabilidad',
      'Contar con RUC para recibos por honorarios',
      'Contar con certificado único laboral vigente',
    ],
    uniformidad: [
      'Chaleco reflectivo y pantalón de trabajo',
      'Polo negro o azul y pantalón jean',
    ],
    descripcion: '<p>En Logística Andina buscamos operarios para nuestro centro de distribución del Callao, una operación que mueve cientos de toneladas de mercadería cada semana para clientes del retail y la industria. Tu labor será clave para que cada pedido salga a tiempo y en perfectas condiciones.</p><p>Serás parte de un equipo de almacén con jefes de turno presentes y compañeros con experiencia que te acompañarán desde el primer día. Los turnos son rotativos y el pago es por turno completo, con posibilidad de continuidad si tu desempeño es bueno.</p><p><strong>Principales funciones:</strong></p><ul><li>Recepción, despacho y traslado de cajas con apoyo de transpaletas</li><li>Control de inventario y ubicación correcta de los productos</li><li>Orden y limpieza permanente dentro del almacén</li><li>Armado de pedidos para clientes de retail y agroindustria</li><li>Soporte en despachos prioritarios de última hora</li><li>Cumplimiento estricto de los protocolos de seguridad</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Ganas de aprender y crecer dentro del equipo</li><li>Buena condición física para tareas de carga y traslado</li><li>Trabajo en equipo y comunicación clara con los jefes de turno</li><li>Puntualidad y disponibilidad inmediata</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Pago puntual por turno completado</li><li>Pago adicional por horas extra en campañas fuertes</li><li>Ambiente de trabajo organizado y jefes de turno presentes</li><li>Equipo de protección incluido</li><li>Posibilidad de volver a trabajar con nosotros cada campaña</li></ul><p><strong>¡Postúlate hoy!</strong> La incorporación se coordina por teléfono y los turnos se asignan por orden de llegada. Las vacantes para esta campaña son limitadas.</p>',
    estado: 'activa',
    fechaPublicacion: '2026-07-20T10:00:00.000Z',
  },
  {
    id: 'v2',
    empresaId: 'u1',
    titulo: 'Estibador temporal',
    categoria: 'estiba',
    distrito: 'Callao',
    sueldo: 95,
    pagoPorHora: 12,
    horarios: ['08:00 a 17:00', '17:00 a 02:00'],
    horario: 'Lun a Vie 8am - 5pm',
    tipoContrato: 'Tiempo completo',
    nivelExperiencia: 'Sin experiencia',
    idiomas: 'Español',
    vacantesDisponibles: 3,
    requisitos: [
      'Fuerza física y actitud responsable',
      'Contar con RUC para recibos por honorarios',
      'Disponibilidad para turnos que incluyen madrugada',
      'Contar con cuenta bancaria BBVA',
    ],
    uniformidad: [
      'Chaleco reflectivo, guantes de seguridad y botas punta de acero',
      'Polo manga larga y pantalón jean azul o negro',
    ],
    descripcion: '<p>¿Tienes fuerza y actitud responsable? Únete al equipo de estibadores de la zona portuaria del Callao, una de las operaciones más dinámicas del país. Aquí cada turno es diferente: recibes contenedores, organizas la carga y aseguras que la mercadería llegue intacta a su destino.</p><p>El trabajo es exigente físicamente, pero se paga de acuerdo al esfuerzo: S/ 12 por hora y S/ 95 por turno completo. Contamos con supervisores en sitio y todo el equipo de seguridad necesario para que trabajes protegido.</p><p><strong>Principales funciones:</strong></p><ul><li>Carga y descarga de mercadería en muelles y almacenes portuarios</li><li>Apoyo a operadores de montacargas en maniobras de traslado</li><li>Acomodo y estiba seguro de cajas y sacos por peso y tamaño</li><li>Revisión visual del estado de la carga y reporte de novedades</li><li>Limpieza del área de trabajo al finalizar el turno</li><li>Manejo responsable de equipos de protección personal</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Acondicionamiento físico acorde al esfuerzo del puesto</li><li>Responsabilidad en turnos que incluyen madrugada</li><li>Capacidad para seguir instrucciones de los supervisores</li><li>Predisposición para trabajar en equipo bajo presión</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Pago por hora con liquidación al cierre de cada turno</li><li>Liquidación diaria sin esperas</li><li>Turnos continuos disponibles toda la semana</li><li>Equipo de seguridad completo en sitio</li><li>Referencia laboral para contrataciones posteriores</li></ul><p><strong>¡Postúlate hoy!</strong> Presenta tu DNI y coordina tu primer turno. Buscamos personas disponibles para incorporarse esta misma semana.</p>',
    estado: 'activa',
    fechaPublicacion: '2026-07-22T10:00:00.000Z',
  },
  {
    id: 'v3',
    empresaId: 'u2',
    titulo: 'Reponedor de tienda',
    categoria: 'reposicion',
    distrito: 'Miraflores',
    sueldo: 60,
    horarios: ['10:00 a 18:00'],
    horario: 'Mar a Dom 10am - 6pm',
    tipoContrato: 'Medio tiempo',
    nivelExperiencia: 'Sin experiencia',
    idiomas: 'Español',
    vacantesDisponibles: 2,
    requisitos: [
      'Buena presencia y actitud de servicio',
      'Disponibilidad de martes a domingo',
      'Experiencia en reposición (deseable)',
    ],
    uniformidad: [
      'Polo provisto por la tienda',
      'Zapatillas o zapatos cerrados',
    ],
    descripcion: '<p>Mega Store de Lima busca reponedores para su tienda de Miraflores, una de las más concurridas de la avenida Larco. Si te gusta el orden y la atención a los detalles, esta es la oportunidad para empezar en el mundo del retail sin experiencia previa.</p><p>Trabajarás de martes a domingo en horario de 10:00 a 18:00, en un ambiente con aire acondicionado y compañeros que te ayudarán a adaptarte rápido. Al finalizar tu jornada, podrás coordinar con el jefe de tienda la continuidad en próximas campañas.</p><p><strong>Principales funciones:</strong></p><ul><li>Reposición de productos en góndolas y vitrinas según planograma</li><li>Revisión de fechas de vencimiento y rotación de stock</li><li>Orden del almacén y del piso de venta</li><li>Atención breve y amable a los clientes que buscan productos</li><li>Armado de exhibidores y carteles de ofertas</li><li>Apoyo al personal de caja en momentos de alta afluencia</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Buena presentación y trato amable con el cliente</li><li>Disposición para mantener el orden en el piso de venta</li><li>Actitud proactiva frente a campañas de temporada</li><li>Sin experiencia previa, pero con ganas de aprender</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Polo de la tienda para tu uniforme</li><li>Horario fijo y continuo</li><li>Descuentos corporativos para colaboradores</li><li>Ambiente seguro y con aire acondicionado</li><li>Referencia laboral para tu currículum</li></ul><p><strong>¡Postúlate hoy!</strong> El puesto es para empezar esta semana. Los horarios se coordinan directamente con el jefe de tienda.</p>',
    estado: 'activa',
    fechaPublicacion: '2026-07-25T10:00:00.000Z',
  },
  {
    id: 'v4',
    empresaId: 'u2',
    titulo: 'Atención al cliente',
    categoria: 'atencion_cliente',
    distrito: 'Miraflores',
    sueldo: 65,
    horarios: ['09:00 a 18:00'],
    horario: 'Lun a Sáb 9am - 6pm',
    tipoContrato: 'Tiempo completo',
    nivelExperiencia: 'Básica',
    idiomas: 'Español e inglés básico',
    vacantesDisponibles: 1,
    descripcion: '<p>Buscamos una persona con vocación de servicio para el área de atención al cliente y caja de Mega Store en Miraflores. Tú serás la primera y última impresión que el cliente lleva de la tienda, por eso valoramos la amabilidad y la buena comunicación.</p><p>El puesto incluye manejo de caja con capacitación incluida: no necesitas experiencia previa, solo actitud para aprender. El horario es de lunes a sábado de 9:00 a 18:00 con descanso de refrigerio incluido.</p><p><strong>Principales funciones:</strong></p><ul><li>Atención en caja: cobros, vueltos y facturación</li><li>Orientación al cliente dentro de la tienda</li><li>Gestión de cambios, devoluciones y consultas</li><li>Reporte de incidencias al jefe de turno</li><li>Arqueo de caja al inicio y cierre de jornada</li><li>Mantenimiento de la limpieza y el orden del puesto de trabajo</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Buena memoria y agilidad con los números</li><li>Amabilidad incluso en horas de mayor afluencia</li><li>Honestidad y manejo cuidadoso del dinero</li><li>Iniciativa para proponer mejoras en el área</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Capacitación de inducción pagada</li><li>Uniforme corporativo incluido</li><li>Bonificación por cumplimiento en campañas</li><li>Horario estable de lunes a sábado</li><li>Posibilidad de pasar a planilla en temporadas altas</li></ul><p><strong>¡Postúlate hoy!</strong> Evaluamos tu perfil en una entrevista rápida de 15 minutos en tienda. El puesto requiere disponibilidad desde la próxima semana.</p>',
    requisitos: ['Buena comunicación y vocación de servicio', 'Manejo de caja (deseable)', 'Disponibilidad de lunes a sábado'],
    uniformidad: ['Blusa o polo negro y pantalón formal oscuro'],
    estado: 'activa',
    fechaPublicacion: '2026-07-28T10:00:00.000Z',
  },
  {
    id: 'v5',
    empresaId: 'u3',
    titulo: 'Promotor de eventos',
    categoria: 'promotoria',
    distrito: 'Surco',
    sueldo: 85,
    pagoPorHora: 10,
    horario: 'Eventos: Sáb y Dom 12pm - 8pm',
    tipoContrato: 'Fin de semana',
    nivelExperiencia: 'Intermedia',
    idiomas: 'Español',
    vacantesDisponibles: 5,
    descripcion: '<p>Festivales del Perú organiza los eventos corporativos más importantes de Lima y está armando su equipo de promotores para la temporada de ferias y lanzamientos. Si disfrutas el trato con el público y las experiencias en vivo, este puesto es para ti.</p><p>Trabajarás los fines de semana (sábado y domingo de 12:00 a 20:00) en sedes de Surco y Miraflores, representando marcas reconocidas en activaciones, degustaciones y eventos empresariales. El pago es de S/ 10 por hora y se entregan polos de la marca.</p><p><strong>Principales funciones:</strong></p><ul><li>Promoción de marca y productos durante el evento</li><li>Recepción y registro de asistentes a la feria</li><li>Apoyo en la instalación de stands y materiales promocionales</li><li>Degustaciones y activaciones de producto</li><li>Manejo de sorteos y dinámicas con el público</li><li>Reporte de resultados de la activación al coordinador</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Carisma y energía frente al público</li><li>Responsabilidad con los horarios de los eventos</li><li>Interés por el marketing y las activaciones de marca</li><li>Disponibilidad ocasional para eventos en otros distritos</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Pago por hora al cierre del evento</li><li>Polos de la marca entregados para ti</li><li>Experiencia en marketing de experiencias</li><li>Refrigerio en jornadas largas</li><li>Contactos y oportunidades para futuros proyectos</li></ul><p><strong>¡Postúlate hoy!</strong> La temporada arranca este fin de semana. Los seleccionados reciben la programación de eventos cada jueves.</p>',
    requisitos: ['Actitud proactiva', 'Experiencia con público'],
    uniformidad: ['Polos entregados por la empresa', 'Pantalón oscuro y zapatos cerrados'],
    estado: 'activa',
    fechaPublicacion: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'v6',
    empresaId: 'u3',
    titulo: 'Personal de limpieza',
    categoria: 'limpieza',
    distrito: 'Surco',
    sueldo: 55,
    horarios: ['07:00 a 12:00'],
    horario: 'Lun a Vie 7am - 12pm',
    tipoContrato: 'Medio tiempo',
    nivelExperiencia: 'Básica',
    requisitos: ['Disponibilidad por las mañanas', 'Experiencia en limpieza de oficinas (deseable)'],
    uniformidad: ['Polos y zapatos antideslizantes entregados por la empresa'],
    descripcion: '<p>Buscamos personal de limpieza para el mantenimiento de oficinas corporativas, salas de eventos y servicios higiénicos en Surco. Un espacio limpio y ordenado habla bien de la empresa y tú serás la persona encargada de lograrlo.</p><p>El horario es de lunes a viernes de 7:00 a 12:00, ideal si buscas trabajo por las mañanas y disponibilidad para otras actividades en la tarde. Todos los materiales de limpieza y el uniforme son proporcionados por la empresa.</p><p><strong>Principales funciones:</strong></p><ul><li>Limpieza y desinfección de oficinas, salas de reuniones y eventos</li><li>Mantenimiento de baños y áreas comunes</li><li>Reposición de insumos de higiene (papel, jabón, toallas)</li><li>Desecho y segregación adecuada de residuos</li><li>Limpieza de vidrios y superficies de uso frecuente</li><li>Reporte de necesidades de mantenimiento al supervisor</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Cuidado con los detalles y las áreas de mayor tránsito</li><li>Honradez y buen manejo de los materiales asignados</li><li>Disponibilidad para empezar temprano</li><li>Referencias del último empleo (deseable)</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Horario fijo por las mañanas, compatible con estudios u otro trabajo</li><li>Materiales de limpieza y uniforme incluidos</li><li>Ambiente tranquilo de oficinas corporativas</li><li>Referencia laboral al culminar el proyecto</li></ul><p><strong>¡Postúlate hoy!</strong> Coordinamos una visita rápida a las instalaciones para que conozcas el lugar antes de tu primer día.</p>',
    estado: 'cerrada',
    fechaPublicacion: '2026-06-10T10:00:00.000Z',
  },
  {
    id: 'v8',
    empresaId: 'u2',
    titulo: 'Operadores para Super Food',
    categoria: 'almacen',
    distrito: 'Miraflores',
    sueldo: 0,
    horarios: ['07:00 a 15:45'],
    horario: '07:00 a 15:45',
    tipoContrato: 'Tiempo completo',
    nivelExperiencia: 'Sin experiencia',
    idiomas: 'Español',
    vacantesDisponibles: 3,
    descripcion: '<p>Super Food, cadena dedicada a la producción y distribución de alimentos, necesita 3 operarios para reforzar su planta de Miraflores desde mañana mismo. Búsqueda urgente para una campaña de abastecimiento que dura varias semanas.</p><p>El horario es de 7:00 a 15:45 con pausa de almuerzo incluida. No se requiere experiencia: la empresa brinda una inducción rápida sobre buenas prácticas de higiene y manipulación de alimentos, por lo que necesitamos personas con carnet de sanidad vigente.</p><p><strong>Principales funciones:</strong></p><ul><li>Recepción y traslado de materia prima al área de producción</li><li>Empacado y etiquetado de productos terminados</li><li>Limpieza y desinfección de mesas y herramientas de trabajo</li><li>Control básico de pesos y cantidades por lote</li><li>Cumplimiento de las normas de higiene y bioseguridad</li><li>Apoyo al equipo de producción en sus tareas diarias</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Higiene personal impecable y carnet de sanidad vigente</li><li>Compromiso con el inicio puntual de la jornada</li><li>Adaptación rápida a un ritmo de producción exigente</li><li>Buena disposición para tareas repetitivas y de detalle</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Incorporación inmediata</li><li>Pago puntual por jornada</li><li>Uniforme y utensilios de higiene incluidos</li><li>Refrigerio de campaña durante el turno</li><li>Posibilidad de continuar en la campaña completa con buena puntualidad</li></ul><p><strong>¡Postúlate hoy!</strong> Es una campaña urgente: los puestos se llenan por orden de postulación. Presenta tu carnet de sanidad al coordinar tu ingreso.</p>',
    requisitos: ['Contar con carnet de sanidad vigente'],
    uniformidad: ['Polo negro, jean azul y zapatillas'],
    estado: 'activa',
    fechaPublicacion: '2026-08-07T08:00:00.000Z',
  },
  {
    id: 'v9',
    empresaId: 'u1',
    titulo: 'Asistente de inventario',
    categoria: 'almacen',
    distrito: 'Callao',
    sueldo: 70,
    horarios: ['08:00 a 17:00'],
    horario: 'Lun a Vie 8am - 5pm',
    tipoContrato: 'Tiempo completo',
    nivelExperiencia: 'Básica',
    idiomas: 'Español',
    vacantesDisponibles: 2,
    requisitos: [
      'Contar con RUC para recibos por honorarios',
      'Experiencia con lectores de código de barras (deseable)',
      'Disponibilidad de lunes a viernes',
      'Contar con certificado único laboral vigente',
    ],
    uniformidad: [
      'Chaleco reflectivo y guantes de trabajo',
      'Polo celeste o azul y pantalón jean',
    ],
    descripcion: '<p>Logística Andina incorpora asistentes de inventario para su almacén del Callao, uno de los centros de distribución más grandes del puerto de Lima. Si tienes orden, buena memoria y te gustan los números, este puesto te ofrece estabilidad de lunes a viernes.</p><p>Trabajarás de 8:00 a 17:00 con jefes de turno presentes y un sistema de conteo claro. El pago es de S/ 70 por jornada con liquidación semanal, y los mejores asistentes tienen prioridad en las campañas de fin de año.</p><p><strong>Principales funciones:</strong></p><ul><li>Conteo cíclico de productos y verificación de stock físico</li><li>Registro de entradas y salidas en el sistema de inventario</li><li>Etiquetado y codificación de mercadería recibida</li><li>Revisión de lotes y fechas de vencimiento</li><li>Reporte de diferencias y mermas al encargado de almacén</li><li>Orden y limpieza de las zonas de trabajo</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Agilidad mental y cuidado con los números</li><li>Disposición para trabajar de pie durante la jornada</li><li>Puntualidad comprobada en trabajos anteriores</li><li>Interés por aprender el uso de sistemas de inventario</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Pago puntual con liquidación semanal</li><li>Horario fijo de lunes a viernes</li><li>Capacitación en el sistema de inventario</li><li>Equipo de seguridad incluido</li><li>Prioridad en campañas de temporada</li></ul><p><strong>¡Postúlate hoy!</strong> Las entrevistas se realizan en el mismo almacén. Trae tu DNI y tu RUC activo para coordinar tu incorporación.</p>',
    estado: 'activa',
    fechaPublicacion: '2026-08-09T09:00:00.000Z',
  },
  {
    id: 'v10',
    empresaId: 'u3',
    titulo: 'Anfitrión de stands',
    categoria: 'eventos',
    distrito: 'Surco',
    sueldo: 80,
    pagoPorHora: 11,
    horarios: ['09:00 a 18:00'],
    horario: 'Eventos: Sáb y Dom 9am - 6pm',
    tipoContrato: 'Fin de semana',
    nivelExperiencia: 'Sin experiencia',
    idiomas: 'Español',
    vacantesDisponibles: 4,
    requisitos: [
      'Buena presencia y trato amable con el público',
      'Disponibilidad para fines de semana',
      'Responsabilidad con la puntualidad en el evento',
    ],
    uniformidad: [
      'Polo de la marca entregado por la empresa',
      'Pantalón oscuro y zapatos cerrados',
    ],
    descripcion: '<p>¿Te gusta recibir a las personas y estar siempre en movimiento? Festivales del Perú busca anfitriones de stands para la feria corporativa que se realizará en Surco. Serás la cara de las marcas más reconocidas durante todo el evento.</p><p>El trabajo es por fines de semana: sábado y domingo de 9:00 a 18:00, con pago de S/ 11 por hora (S/ 80 por jornada completa). Recibirás una inducción corta cada mañana antes de abrir la feria, así sabrás siempre qué transmitir a los visitantes.</p><p><strong>Principales funciones:</strong></p><ul><li>Recepción y orientación de los asistentes al stand</li><li>Entrega de material informativo y cotizaciones simples</li><li>Registro de contactos y leads del evento</li><li>Apoyo en demostraciones de producto</li><li>Manejo del orden y la imagen del stand</li><li>Reporte final de atenciones al coordinador</li></ul><p><strong>¿Qué buscamos?</strong></p><ul><li>Sonrisa y energía para jornadas largas de pie</li><li>Facilidad para hablar con personas desconocidas</li><li>Respeto de los horarios de la feria</li><li>Sin experiencia previa, con muchas ganas</li></ul><p><strong>¿Qué ofrecemos?</strong></p><ul><li>Pago por hora liquidado al cierre del evento</li><li>Polo de la marca para conservarlo</li><li>Refrigerio durante la jornada</li><li>Experiencia real en ferias corporativas</li><li>Preferencia en próximos eventos de la temporada</li></ul><p><strong>¡Postúlate hoy!</strong> Los anfitriones se confirman un día antes de cada evento. Si cumples bien, estarás en la programación del mes completo.</p>',
    estado: 'activa',
    fechaPublicacion: '2026-08-10T10:00:00.000Z',
  },
];

export const postulacionesIniciales = [
  { id: 'p1', vacanteId: 'v1', trabajadorId: 'u4', estado: 'aceptado', fechaPostulacion: '2026-07-21T10:00:00.000Z' },
  { id: 'p2', vacanteId: 'v1', trabajadorId: 'u5', estado: 'pendiente', fechaPostulacion: '2026-07-23T10:00:00.000Z' },
  { id: 'p3', vacanteId: 'v2', trabajadorId: 'u6', estado: 'revisado', fechaPostulacion: '2026-07-22T12:00:00.000Z' },
  { id: 'p4', vacanteId: 'v3', trabajadorId: 'u7', estado: 'pendiente', fechaPostulacion: '2026-07-26T10:00:00.000Z' },
  { id: 'p5', vacanteId: 'v3', trabajadorId: 'u4', estado: 'pendiente', fechaPostulacion: '2026-07-27T10:00:00.000Z' },
  { id: 'p6', vacanteId: 'v4', trabajadorId: 'u8', estado: 'revisado', fechaPostulacion: '2026-07-29T10:00:00.000Z' },
  { id: 'p7', vacanteId: 'v5', trabajadorId: 'u5', estado: 'aceptado', fechaPostulacion: '2026-08-02T10:00:00.000Z' },
  { id: 'p8', vacanteId: 'v6', trabajadorId: 'u6', estado: 'rechazado', fechaPostulacion: '2026-06-12T10:00:00.000Z' },
];

export const calificacionesIniciales = [
  { id: 'c1', deUsuarioId: 'u1', aUsuarioId: 'u4', puntaje: 5, comentario: 'Muy puntual y responsable.', fecha: '2026-07-30T10:00:00.000Z' },
  { id: 'c2', deUsuarioId: 'u1', aUsuarioId: 'u6', puntaje: 4, comentario: 'Buen trabajo, un poco lento.', fecha: '2026-06-15T10:00:00.000Z' },
  { id: 'c3', deUsuarioId: 'u3', aUsuarioId: 'u5', puntaje: 5, comentario: 'Excelente actitud en el evento.', fecha: '2026-08-05T10:00:00.000Z' },
];